import Head from "next/head";
import type { Metadata } from "next";
// REACT-CUSTOM-ALERT
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// STYLES
import "./utils/constants/styles/globals.css";

// Les Metadata servent :
// ✅ Meilleur SEO (meilleur classement Google)
// ✅ Amélioration du partage social (meilleure prévisualisation des liens), (Cards et Open Graph : L'Open Graph améliore l'affichage des liens sur Facebook, LinkedIn, WhatsApp, etc..., Twitter)
// ✅ Personnalisation facile et centralisation des Metadata
// On utilise un objet metadata dans layout.tsx/jsx ou page.tsx/jsx.
export const metadata: Metadata = {
  title: {
    absolute: "Net Movie",
    default: "Net Movie",
    template: "%s - Net Movie",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head>
        <title>Mon Site Web - Page d'Accueil</title>
        <meta name='description' content="Description de ma page d'accueil" />
        <meta name='keywords' content='site web, next.js, SEO, optimisation' />
        <meta name='author' content='Yoann Croguennec' />
        <meta name='robots' content='index, follow' />
        <link rel='canonical' href='https://ton-site.com/' />
      </Head>
      <body>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
